### ISSUE TITLE
[BUG] testexec/do.to2.62.execute.go:119 panic error

### ISSUE THREAD

**Issue by quanvincss** [fido-alliance/iot-fdo-conformance-tools#45]
To simplify issue resolution process, please provide network logs, and or test voucher.
```
2023/09/27 10:44:21 Requesting GetOVNextEntry62 for entry 0 
2023/09/27 10:44:21 Requesting GetOVNextEntry62 for entry 1 
2023/09/27 10:44:21 Requesting GetOVNextEntry62 for entry 2 
2023/09/27 10:44:21 Requesting GetOVNextEntry62 for entry 0 
2023/09/27 10:44:21 http: panic serving [::1]:62577: runtime error: invalid memory address or nil pointer dereference
goroutine 163 [running]:
net/http.(*conn).serve.func1()
        /Users/thaodtp/sdk/go1.19.5/src/net/http/server.go:1850 +0xb0
panic({0x1033cca80, 0x103862f50})
        /Users/thaodtp/sdk/go1.19.5/src/runtime/panic.go:890 +0x258
github.com/fido-alliance/fdo-fido-conformance-server/testexec.executeTo2_62({{}, {0x1400b0f0190, 0x10, 0x10}, {0x140002cc270, 0x15}, 0x2, 0x1400037d050, 0x0, {{}, ...}, ...}, ...)
        /Users/thaodtp/Documents/work/projects/FDO/FA/fdo-fido-conformance-server/testexec/do.to2.62.execute.go:119 +0x93c
github.com/fido-alliance/fdo-fido-conformance-server/testexec.ExecuteDOTestsTo2({{}, {0x1400b0f0190, 0x10, 0x10}, {0x140002cc270, 0x15}, 0x2, 0x1400037d050, 0x0, {{}, ...}, ...}, ...)
```

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [x] Device Onboarding Service
- [ ] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [x] TO2

## Issue description
- API called: `/api/dot/execute`

**Comment by herrjemand** [comment]
Addressed
